version: '3.7'

services:
  db:
    image: mdillon/postgis:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    volumes:
      - ./geotracker:/app
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
